version: "3.4"

services:
    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
        - 9090:9090
    
    test-app:
        build: .
        command: bash -c "./bin/test-app"
    
    test-app2:
        build: .
        command: bash -c "./bin/test-app"

